name: Telegram Auto Poster

# Скрипт запускается только при пуше в основную ветку и только если изменился файл data.js
on:
  push:
    branches:
      - main 
    paths:
      - 'data.js' 

jobs:
  send_post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run posting script
        env:
          BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python send_to_telegram.py
